# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bab168b4fcd1b58bf6708e8804ab037ba998a1354f3b61d14350bfa0d41c2a9d9bbd490bbe589bfa2cb365587ee65d5a38f06868f9a654cfe4f64ef3939f6c1

test:
  secret_key_base: e976fc3830e5856c6b39e1ba30ef329ea09481b49861607194c26c4209aa9ed2ab8a5d7b89ee2dfd8a58e5524de017fb5b180affabf86427418df506510c73e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
